CREATE TABLE users (
id SERIAL PRIMARY KEY,
username VARCHAR(90) UNIQUE,
hashedPassword VARCHAR(90)
);

CREATE TABLE organizations (
id SERIAL PRIMARY KEY,
name VARCHAR(80),
x FLOAT,
y FLOAT,
creationDate TIMESTAMP,
annualTurnover FLOAT,
fullName VARCHAR(80),
employeesCount INT,
organizationType VARCHAR(10),
addressName VARCHAR(80),
locationX FLOAT,
locationY FLOAT,
locationName VARCHAR(80),
creatorID INT REFERENCES users(id)
);